spring.application.name=distributed-job-scheduler

# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:mysql://localhost:3307/job_scheduler?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=new_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# NODE CONFIG (IMPORTANT FIX)
# =========================
# MUST be provided via environment variable
node.id=${NODE_ID:node-default}
node.host=localhost

# Dynamic port support
server.port=${PORT:8082}

# =========================
# SCHEDULER SETTINGS
# =========================
scheduler.check-interval=1000
scheduler.heartbeat-interval=5000

# Node will be marked DEAD if no heartbeat in this time (ms/seconds based on your logic)
scheduler.dead-threshold=15


# $env:PORT=8083; $env:NODE_ID="node-3"; mvn spring-boot:run
